[workspace]
resolver = "2"

members = [
    "a2015",
    "a2016",
    "a2017",
    "a2018",
    "a2019",
    "a2020",
    "a2021",
    "a2022",
    "a2023",
    "a2024",
    "a2025",
    "util",
]

[profile.dev]
opt-level = 1

[patch.crates-io]
lowdim = { path = "../lowdim" }
