[package]
edition = "2024"
name = "a2025"
version = "0.1.0"
authors = ["Juergen Stuber <juergen@jstuber.net>"]
license = "MIT OR Apache-2.0"

[dependencies]
lowdim = "0.7.2"
nom = "7.0.0"
util = { version = "0.1.0", path = "../util" }
